### ISSUE TITLE
Table with Existing rows

### ISSUE THREAD

**Issue by iamkevla** [knowthen/BindTable#1]
I am not sure if I am following things here but is there an assumption that the table you are binding to is empty. How would you handle a table with existing records?

**Comment by knowthen** [comment]
A couple options for getting the initial dataset:
If you your changefeed includes an orderBy and a limit, the initial records get streamed as shown below

``` javascript
r.db('demo1').table('person')
  .orderBy({index: 'age'})
  .limit(2)
  .changes()
```

Provides an initial stream like

``` javascript
[{
  "new_val": {
    "age": 29 ,
    "id":  "5cb6f989-2aaf-41d2-8e79-38f1781b091f" ,
    "name":  "Bob"
  }
} ,{
  "new_val": {
    "age": 36 ,
    "id":  "f17ba9ff-12e1-4c78-911d-feb3b3f1b717" ,
    "name":  "Joe"
  }
}]
```

which will populate the rows attribute.

This doesn't work for all scenarios, so another possibility is to start the changefeed which results in potentially zero initial records, then query an initial dataset and send these values as an array of 'new_val' records.  

For example the following changefeed won't stream an initial set of records, just a stream of changes.  So you could start this query

``` javascript
r.db('demo1').table('person')
  .filter(function(row){
    return row('age').ge(18);
  }).changes().run({cursor: true}, handleChange);;
```

then you could run the following query, which will provide an initial set of records

``` javascript
var records = yield r.db('demo1').table('person')
  .filter(function(row){
    return row('age').ge(18);
  }).run();
```

then manipulate the results to be sent as if they were change records, ie make an array of objects such as

``` javascript
var initialSet = [];
records.forEach(function(record){
  initialSet.push(
    new_val: record
  );
});
socket.emit('person:changes', initialSet);
```

I think this is probably fine for most cases but I can see some potential problems with this approach... I am going to give it some thought and see if there is a more graceful approach.

**Comment by iamkevla** [comment]
Thanks for the quick response. I can see now what I was doing wrong. Thanks
