### ISSUE TITLE
Education Request

### ISSUE THREAD

**Issue by MadBomber** [knowthen/BindTable#3]
Hello James, it was by a lucky accident that I recently saw your video on real-time webapps using RethinkDB.  (Well done by the way.)   I have been thinking about doing a brown-bag kind of demo to show off the kinds of things that the RethinkDB streaming change set can do.  Your question app looked like a nice place to start.  To start educating myself on your example, I started with the BindTable library.

However, being a complete loon (aka old dog who doesn't do front end work) when it comes to javascript and node junk,  I have a basic toolchain-related question.

This is what I have done so far:

1) I have cloned your BindTable repo to a local working directory.
2) in that directory I did 'npm install' to get the dependent packages

Now I want to run your tests on the library so I did 'karma run' and got the message:

``` bash
[2015-12-07 14:04:23.078] [DEBUG] config - Loading config .../madbomber/BindTable/karma.conf.js
There is no server listening on port 9876
```

What should I have done first before attempting to run the test suite?  I'm assuming that there is some kind of default server that should start on port 9876.

Intent-related:
You have not touched the BindTable repo since the spring.  Is BindTable just an experiment or do you think that it is "production" ready?

Dewayne
  o-*

**Comment by knowthen** [comment]
Hi Dewayne, I just looked at the test command in the package.json it was
all screwed for some reason... Must have been a bad day for me :)

I just updated it in the repo.
Essentially after installing dependancies w/ npm install, you run the
following command:
./node_modules/karma/bin/karma start --browsers Chrome --single-run

In regards to the library. It was mostly an experiment that I'm not sure is
a good idea, though it does demo well...  It just doesn't feel right to me,
abstracting the mutations in the array seems like it'll be problematic when
you move beyond trivial apps.  It seems like using immutables is a better
practice.

I've been using reactjs on the front end mostly for the last 6-9 months and
it doesn't fit well in the React world at all.

"Production Ready", probably not.  I've just used it in a couple demo apps,
but it's a simple enough library that could be hacked on as needed.

Best,
James

On Mon, Dec 7, 2015 at 12:22 PM, Dewayne VanHoozer <notifications@github.com

**Comment by MadBomber** [comment]
> On Dec 7, 2015, at 4:43 PM, James Moore notifications@github.com wrote:
> 
> Must have been a bad day for me :)

Everyday I work with Java\* stuff is a bad day for me.  I've refreshed my fork and run the tests successfully.  I now have your baseline from which to ponder.  Thank you.  Lets close this issue.

Dewayne
  o-*

**Comment by GeoffreyPlitt** [comment]
@knowthen have you come across any BindTable react/redux examples? would love to see how that would work.

**Comment by knowthen** [comment]
I wouldn't recommend it... This library was just an experiment.. at this point I don't think is a good option..  I'm more inclined to go the functional/immutable data route now days, this library is quite contrary to the principles of functional programming / immutable data.
